import type { Metadata } from "next";
import "./globals.css";
import {
  monument,
  satoshiBold,
  satoshiMedium,
  satoshiRegular,
} from "@/utils/globalFonts";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monument.variable} ${satoshiBold.variable} ${satoshiMedium.variable} ${satoshiRegular.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
